networks:
  backend:
    external: true

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    networks:
      - backend
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM} #optional
    volumes:
      - /opt/plex/config:/config
      - /mnt/media1/Videos/Shows:/tv
      - /mnt/media2/Videos/Shows:/tv2
      - /mnt/media1/Videos/Movies:/movies
      - /mnt/media2/Videos/Movies:/movies2
      - /mnt/media1/Music:/music
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=backend"
      - "io.traefik.instance=private"
      - "traefik.http.routers.plex-secure.entrypoints=https"
      - "traefik.http.routers.plex-secure.rule=Host(`plex.big-melpert.ratsnest.dev`)"
      - "traefik.http.routers.plex-secure.tls=true"
      - "traefik.http.services.plex-secure.loadbalancer.server.port=32400"
      - "traefik.http.services.plex-secure.loadbalancer.server.scheme=http" 
