# Variables that will need to be changed:
#     <PUID>                            -  User id for folder/file permissions
#     <PGID>                            -  Group id for folder/file permissions
#     <PATH_TO_CONFIG>                  -  Path where Unmanic will store config files
#     <PATH_TO_LIBRARY>                 -  Path where you store the files that Unmanic will scan
#     <PATH_TO_ENCODE_CACHE>            -  Cache path for in-progress encoding tasks
#

networks:
  proxy:
    external: true

services:
  unmanic:
    container_name: unmanic
    image: josh5/unmanic:latest
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /opt/unmanic/config:/config
      - /mnt/media1:/media1
      - /mnt/media2:/media2
      - /tmp/unmanic:/tmp/unmanic
    devices:
      - /dev/dri:/dev/dri # For H/W transcoding using the VAAPI encoder
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=backend"
      - "io.traefik.instance=internal"
      - "traefik.http.routers.unmanic-secure.entrypoints=https"
      - "traefik.http.routers.unmanic-secure.rule=Host(`unmanic.rocky-melpert.ratsnest.dev`)"
      - "traefik.http.routers.unmanic-secure.tls=true"
      - "traefik.http.services.unmanic-secure.loadbalancer.server.port=8888"
      - "traefik.http.services.unmanic-secure.loadbalancer.server.scheme=http"
